version: '3.2'

services:
  gateway:
    image: microsoft/application
    ports:
      - "5010:80"
    volumes:
      - ./SocialApp.Gateway.Api:/app
    working_dir: /app
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
      - auth
      - core
      - client
  
  auth:
    image: microsoft/application
    ports:
      - "5001:80"
    volumes:
      - ./:/app
    working_dir: /app/SocialApp.UserManagement
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
      - db
  
  core:
    image: microsoft/application
    ports:
      - "5002:80"
    volumes:
      - ./:/app
    working_dir: /app/SocialApp.AppManagement
    command: [ 'dotnet', 'watch', 'run' ]
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server"
    environment:
        SA_PASSWORD: "Password1;"
        ACCEPT_EULA: "Y"

  client:
    image: microsoft/application
    ports:
    - "5003:80"
    volumes:
    - ./:/app
    working_dir: /app/socialapp.client
    command: [ 'npm', 'start' ]
